CREATE TABLE `board` (
	`no`	int NOT NULL AUTO_INCREMENT,
	`title`	VARCHAR(100)	NOT NULL	COMMENT '제목',
	`writer` VARCHAR(100)	 NOT NULL	COMMENT '작성자',
	`content`	TEXT	NULL	COMMENT '내용',
	`created_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '등록일자',
	`updated_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '수정일자',
	PRIMARY KEY (`no`)
);